import { useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import Screen from '../components/Screen';
import { register } from '../services/auth';

export default function Register() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [submitting, setSubmitting] = useState(false);
  async function submit() { if (!email || !password) return Alert.alert('Missing details', 'Enter an email and password.'); if (password.length < 6) return Alert.alert('Password too short', 'Use at least 6 characters.'); if (password !== confirmPassword) return Alert.alert('Passwords do not match', 'Enter the same password twice.'); setSubmitting(true); try { await register(email, password); router.replace('/dashboard'); } catch (error) { Alert.alert('Unable to create account', error.message); } finally { setSubmitting(false); } }
  return <Screen noNav><View style={s.page}><Text style={s.title}>Create account</Text><Text style={s.copy}>Create an account to access SortIQ securely.</Text><TextInput style={s.input} value={email} onChangeText={setEmail} autoCapitalize="none" autoCorrect={false} keyboardType="email-address" placeholder="Email address"/><TextInput style={s.input} value={password} onChangeText={setPassword} secureTextEntry placeholder="Password (at least 6 characters)"/><TextInput style={s.input} value={confirmPassword} onChangeText={setConfirmPassword} secureTextEntry placeholder="Confirm password"/><TouchableOpacity style={[s.button, submitting && s.disabled]} disabled={submitting} onPress={submit}><Text style={s.buttonText}>{submitting ? 'Creating account…' : 'Create account'}</Text></TouchableOpacity><TouchableOpacity onPress={() => router.back()}><Text style={s.link}>Already have an account? Sign in</Text></TouchableOpacity></View></Screen>;
}
const s = StyleSheet.create({ page: { padding: 20, gap: 14 }, title: { fontSize: 30, fontWeight: '800', color: '#183124', marginTop: 20 }, copy: { color: '#617467', lineHeight: 20 }, input: { backgroundColor: '#FFF', borderWidth: 1, borderColor: '#DCE9DE', borderRadius: 12, padding: 15, color: '#183124' }, button: { backgroundColor: '#137A42', padding: 16, borderRadius: 14, alignItems: 'center' }, disabled: { opacity: .6 }, buttonText: { color: '#FFF', fontWeight: '800' }, link: { color: '#137A42', fontWeight: '700', textAlign: 'center', padding: 8 } });
